"""Markdown export for audit reports."""

from reports.scoring import AuditReport


class MarkdownExporter:
    """Convert an AuditReport to a clean Markdown document."""

    def export(self, report: AuditReport) -> str:
        lines = [
            f"# GTM Audit Report: {report.company_name}",
            "",
            f"**URL:** {report.company_url}",
            f"**Date:** {report.audit_date}",
            f"**Type:** {report.audit_type.capitalize()} Audit",
            f"**Overall Score:** {report.overall_percentage:.0f}/100 ({report.overall_grade.value})",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
        ]

        # Strengths
        strengths = report.get_top_strengths(5)
        if strengths:
            lines.append("### Strengths")
            for s in strengths:
                lines.append(f"- {s}")
            lines.append("")

        # Critical gaps
        gaps = report.get_critical_gaps(5)
        if gaps:
            lines.append("### Critical Gaps")
            for g in gaps:
                lines.append(f"- {g}")
            lines.append("")

        # Quick wins
        quick_wins = report.get_quick_wins(5)
        if quick_wins:
            lines.append("### Quick Wins (High Impact, Low Effort)")
            for qw in quick_wins:
                lines.append(f"- **{qw.area}:** {qw.issue} — {qw.recommendation}")
            lines.append("")

        lines.extend(["---", ""])

        # Module sections
        for module in report.modules:
            lines.append(f"## {module.name}")
            if module.items:
                lines.append(
                    f"**Score:** {module.percentage:.0f}% | "
                    f"**Grade:** {module.grade.value}"
                )
            lines.append("")

            if module.analysis_text:
                lines.append(module.analysis_text)
                lines.append("")

            if module.strengths:
                lines.append("### Strengths")
                for s in module.strengths:
                    lines.append(f"- {s}")
                lines.append("")

            if module.weaknesses:
                lines.append("### Areas for Improvement")
                for w in module.weaknesses:
                    lines.append(f"- {w}")
                lines.append("")

            if module.recommendations:
                lines.append("### Recommendations")
                for rec in module.recommendations:
                    lines.append(
                        f"\n**{rec.issue}** "
                        f"(Impact: {rec.impact.value}, Effort: {rec.effort.value})"
                    )
                    lines.append(f"> {rec.recommendation}")
                    if rec.implementation_steps:
                        lines.append("\nSteps:")
                        for i, step in enumerate(rec.implementation_steps, 1):
                            lines.append(f"  {i}. {step}")
                    if rec.success_metrics:
                        lines.append(f"\nMetrics: {', '.join(rec.success_metrics)}")
                lines.append("")

            lines.extend(["---", ""])

        # Prioritized action plan
        all_recs = report.get_all_recommendations()[:20]
        if all_recs:
            lines.append("## Prioritized Action Plan")
            lines.append("")
            for i, rec in enumerate(all_recs, 1):
                lines.append(
                    f"{i}. **[{rec.area}]** {rec.issue} — {rec.recommendation} "
                    f"(Impact: {rec.impact.value}, Effort: {rec.effort.value}"
                    f"{', Timeline: ' + rec.timeline if rec.timeline else ''})"
                )
            lines.append("")

        lines.extend([
            "---",
            "",
            f"*Generated by GTM Audit Platform — Bhavsar Growth Consulting — {report.audit_date}*",
        ])

        return "\n".join(lines)
